    - name: Commit and push changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add config.json
        # Controlla se ci sono modifiche prima di fare il commit
        if git diff --staged --quiet; then
          echo "Nessuna modifica trovata in config.json. Il commit non è necessario."
        else
          git commit -m "Aggiornamento domini in config.json"
          git push origin main  # Assicura che il main venga aggiornato

          # Recupera tutti i branch remoti e aggiorna quelli esistenti
          git fetch --all

          for branch in $(git branch -r | grep -v HEAD | sed 's/origin\///'); do
            if [ "$branch" != "main" ]; then
              echo "Aggiornamento del branch: $branch"
              git checkout $branch || git checkout -b $branch origin/$branch
              git merge main --no-edit  # Unisce le modifiche dal main
              git push origin $branch
            fi
          done

          # Torna su main alla fine
          git checkout main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
